### ISSUE TITLE
Simulate insertion speed?

### ISSUE THREAD

**Issue by deklanw** [MaterializeInc/tb#21]
It would be convenient if you could specify an upper bound on insertion speed (for purposes of testing performance)

**Comment by rjnn** [comment]
I'm not sure I'm following here - what do you mean by 'upper bound on insertion speed'? As in you want `tb` to rate limit the inserts when it first dumps out of the database, so that you can use a large static database, run `tb` with different `max_insertion_speed` settings to measure how fast Materialize can ingest?

**Comment by deklanw** [comment]
Yes, exactly that. Maybe it would make more sense on Materialized's end for a given source.

**Comment by rjnn** [comment]
I believe we have looked at this before. The reason we didn't add it is because Kafka already has a "max consumer throughput" setting that allows the Kafka cluster to rate limit consumers.

I still think it makes sense for us to have some controls in Materialize for this. Related: MaterializeInc/materialize#3382.
